### ISSUE TITLE
Keeps getting the same Error.

### ISSUE THREAD

**Issue by ifaarix** [SuchZNC/zncbot#9]
I have setup the bot, configured and all. It is connected to network and znc. I can see the channels chats through terminal, but none of the cmds work, it keeps on giving:
 " DEBUG:root:RECV: :*send_raw!znc@znc.in PRIVMSG admin90879 :User [znc] not found "

Am i missing something here?

**Comment by nolsen42** [comment]
Seems like an issue either with the configuration for identify-msg, or a bug related to identify-msg

**Comment by nolsen42** [comment]
This issue has been solved over on IRC, so I'll be closing this.
